version: '3.6'
services:
  web:
    build:
      context: "./"
      dockerfile: Dockerfile.dev
    networks:
      - ship
    environment:
      NODE_ENV: development
      HRM_HOST: "0.0.0.0"
    ports:
      - "3002:3002"
      - "8081:8081"

networks:
  ship:
    name: ship_network
